[project]
name = "amaranth-stubs"
version = "2024.05.16.dev0"
dependencies = [
    "amaranth @ git+https://github.com/amaranth-lang/amaranth@115954b4d957b4ba642ad056ab1670bf5d185fb6"
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]

[project.optional-dependencies]
dev = [
    "pyright == 1.1.332"
]

[tool.pyright]
include = ["amaranth-stubs", "amaranth_types"]
