[project]
name = "amaranth-stubs"
version = "2024.05.16.dev0"
dependencies = [
    "amaranth @ git+https://github.com/amaranth-lang/amaranth@f48b8650c4df42b3260c4791b18fad7991af0541"
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]

[project.optional-dependencies]
dev = [
    "pyright == 1.1.332"
]

[tool.pyright]
include = ["amaranth-stubs", "amaranth_types"]
