"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod
from collections.abc import Callable, Iterator, MutableMapping, MutableSequence, MutableSet, Iterable, Mapping, Sequence
from typing import Generic, NoReturn, Optional, TypeVar, final, overload
from enum import Enum, EnumMeta
from amaranth_types import ValueLike, FlatValueLike, ShapeLike, FlatShapeLike, StatementLike
from amaranth_types.types import IOValueLike, SwitchKey
from amaranth.lib.enum import EnumView, FlagView, _T_Enum, _T_Flag

__all__: list[str] = [
    "SyntaxError",
    "SyntaxWarning",
    "Shape",
    "signed",
    "unsigned",
    "ShapeCastable",
    "ShapeLike",
    "Value",
    "Const",
    "C",
    "AnyValue",
    "AnyConst",
    "AnySeq",
    "Operator",
    "Mux",
    "Part",
    "Slice",
    "Cat",
    "Concat",
    "SwitchValue",
    "Array",
    "ArrayProxy",
    "Signal",
    "ClockSignal",
    "ResetSignal",
    "ValueCastable",
    "ValueLike",
    "Initial",
    "Format",
    "Statement",
    "Switch",
    "Property",
    "Assign",
    "Print",
    "Assert",
    "Assume",
    "Cover",
    "IOValue",
    "IOPort",
    "IOConcat",
    "IOSlice",
    "SignalKey",
    "SignalDict",
    "SignalSet",
]

T = TypeVar("T")
U = TypeVar("U")
_T_ShapeCastable = TypeVar("_T_ShapeCastable", bound=ShapeCastable, default=ShapeCastable, covariant=True)
_T_ValueCastable = TypeVar("_T_ValueCastable", bound=ValueCastable, default=ValueCastable, covariant=True)
Flattenable = T | Iterable[Flattenable[T]]

class SyntaxError(Exception):
    pass

class SyntaxWarning(Warning):
    pass

class DUID:
    """Deterministic Unique IDentifier."""

    __next_uid = ...
    def __init__(self) -> None: ...

class ShapeCastable(Generic[U]):
    """
    Interface class for objects that can be cast to a :class:`Shape`.

    Shapes of values in the Amaranth language are specified using :ref:`shape-like objects
    <lang-shapelike>`. Inheriting a class from :class:`ShapeCastable` and implementing all of
    the methods described below adds instances of that class to the list of shape-like objects
    recognized by the :meth:`Shape.cast` method. This is a part of the mechanism for seamlessly
    extending the Amaranth language in third-party code.

    To illustrate their purpose, consider constructing a signal from a shape-castable object
    :py:`shape_castable`:

    .. code::

        value_like = Signal(shape_castable, init=initializer)

    The code above is equivalent to:

    .. code::

        value_like = shape_castable(Signal(
            shape_castable.as_shape(),
            init=shape_castable.const(initializer)
        ))

    Note that the :py:`shape_castable(x)` syntax performs :py:`shape_castable.__call__(x)`.

    .. tip::

        The source code of the :mod:`amaranth.lib.data` module can be used as a reference for
        implementing a fully featured shape-castable object.
    """
    def __init__(self, *args, **kwargs) -> None: ...
    def __init_subclass__(cls, **kwargs) -> None: ...
    def as_shape(self, *args, **kwargs) -> ShapeLike:
        """
        as_shape()

        Convert :py:`self` to a :ref:`shape-like object <lang-shapelike>`.

        This method is called by the Amaranth language to convert :py:`self` to a concrete
        :class:`Shape`. It will usually return a :class:`Shape` object, but it may also return
        another shape-like object to delegate its functionality.

        This method must be idempotent: when called twice on the same object, the result must be
        exactly the same.

        This method may also be called by code that is not a part of the Amaranth language.

        Returns
        -------
        Any other object recognized by :meth:`Shape.cast`.

        Raises
        ------
        Exception
            When the conversion cannot be done. This exception must be propagated by callers
            (except when checking whether an object is shape-castable or not), either directly
            or as a cause of another exception.
        """
        ...
    def __call__(self, target: ValueLike) -> U:
        """
        __call__(obj)

        Lift a :ref:`value-like object <lang-valuelike>` to a higher-level representation.

        This method is called by the Amaranth language to lift :py:`obj`, which may be any
        :ref:`value-like object <lang-valuelike>` whose shape equals :py:`Shape.cast(self)`,
        to a higher-level representation, which may be any value-like object with the same
        shape. While not constrained here, usually a :class:`ShapeCastable` implementation will
        be paired with a :class:`ValueCastable` implementation, and this method will return
        an instance of the latter.

        If :py:`obj` is not as described above, this interface does not constrain the behavior
        of this method. This may be used to implement another call-based protocol at the same
        time.

        For any compliant :py:`obj`, the following condition must hold:

        .. code::

            Value.cast(self(obj)) == Value.cast(obj)

        This method may also be called by code that is not a part of the Amaranth language.

        Returns
        -------
        A :ref:`value-like object <lang-valuelike>`.
        """
        ...
    def const(self, *args, **kwargs) -> ValueLike:
        """
        const(obj)

        Convert a constant initializer :py:`obj` to its value representation.

        This method is called by the Amaranth language to convert :py:`obj`, which may be an
        arbitrary Python object, to a concrete :ref:`value-like object <lang-valuelike>`.
        The object :py:`obj` will usually be a Python literal that can conveniently represent
        a constant value whose shape is described by :py:`self`. While not constrained here,
        the result will usually be an instance of the return type of :meth:`__call__`.

        For any :py:`obj`, the following condition must hold:

        .. code::

            Shape.cast(self) == Const.cast(self.const(obj)).shape()

        This method may also be called by code that is not a part of the Amaranth language.

        Returns
        -------
        A :ref:`value-like object <lang-valuelike>` that is :ref:`constant-castable <lang-constcasting>`.

        Raises
        ------
        Exception
            When the conversion cannot be done. This exception must be propagated by callers,
            either directly or as a cause of another exception. While not constrained here,
            usually the exception class will be :exc:`TypeError` or :exc:`ValueError`.
        """
        ...
    def from_bits(self, raw: int):
        """
        Lift a bit pattern to a higher-level representation.

        This method is called by the Amaranth language to lift :py:`raw`, which is an :class:`int`,
        to a higher-level representation, which may be any object accepted by :meth:`const`.
        Most importantly, the simulator calls this method when the value of a shape-castable
        object is retrieved.

        For any valid bit pattern :py:`raw`, the following condition must hold:

        .. code::

            Const.cast(self.const(self.from_bits(raw))).value == raw

        While :meth:`const` will usually return an Amaranth value or a custom value-castable
        object that is convenient to use while constructing the design, this method will usually
        return a Python object that is convenient to use while simulating the design. While not
        constrained here, these objects should have the same type whenever feasible.

        This method may also be called by code that is not a part of the Amaranth language.

        Returns
        -------
        unspecified type

        Raises
        ------
        Exception
            When the bit pattern isn't valid. This exception must be propagated by callers,
            either directly or as a cause of another exception. While not constrained here,
            usually the exception class will be :exc:`ValueError`.
        """
        ...
    def format(self, obj: ValueLike, spec: str) -> Format:
        """
        Format a value.

        This method is called by the Amaranth language to implement formatting for custom
        shapes. Whenever :py:`"{obj:spec}"` is encountered by :class:`Format`, and :py:`obj`
        has a custom shape that has a :meth:`format` method, :py:`obj.shape().format(obj, "spec")`
        is called, and the format specifier is replaced with the result.

        The default :meth:`format` implementation is:

        .. code::

            def format(self, obj, spec):
                return Format(f"{{:{spec}}}", Value.cast(obj))

        Returns
        -------
        :class:`Format`
        """
        ...

class Shape:
    """
    Bit width and signedness of a :class:`Value`.

    A :class:`Shape` can be obtained by:

    * constructing with explicit bit width and signedness;
    * using the :func:`signed` and :func:`unsigned` aliases if the signedness is known upfront;
    * casting from a variety of objects using the :meth:`cast` method.

    Parameters
    ----------
    width : int
        The number of bits in the representation of a value. This includes the sign bit for signed
        values. Cannot be zero if the value is signed.
    signed : bool
        Whether the value is signed. Signed values use the
        `two's complement <https://en.wikipedia.org/wiki/Two's_complement>`_ representation.
    """
    @property
    def width(self) -> int: ...
    @property
    def signed(self) -> bool: ...
    def __init__(self, width: int = ..., signed: bool = ...) -> None: ...
    @staticmethod
    def cast(obj: ShapeLike, *, src_loc_at=...) -> Shape:
        """
        Cast :py:`obj` to a shape.

        Many :ref:`shape-like <lang-shapelike>` objects can be cast to a shape:

        * a :class:`Shape`, where the result is itself;
        * an :class:`int`, where the result is :func:`unsigned(obj) <unsigned>`;
        * a :class:`range`, where the result has minimal width required to represent all elements
          of the range, and is signed if any element of the range is signed;
        * an :class:`enum.Enum` whose members are all :ref:`constant-castable <lang-constcasting>`
          or :class:`enum.IntEnum`, where the result is wide enough to represent any member of
          the enumeration, and is signed if any member of the enumeration is signed;
        * a :class:`ShapeCastable` object, where the result is obtained by repeatedly calling
          :meth:`obj.as_shape() <ShapeCastable.as_shape>`.

        Raises
        ------
        TypeError
            If :py:`obj` cannot be converted to a :class:`Shape`.
        RecursionError
            If :py:`obj` is a :class:`ShapeCastable` object that casts to itself.
        """
        ...
    def __repr__(self) -> str:
        """
        Python code that creates this shape.

        Returns :py:`f"signed({self.width})"` or :py:`f"unsigned({self.width})"`.
        """
        ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

def unsigned(width: int) -> Shape:
    """Returns :py:`Shape(width, signed=False)`."""
    ...

def signed(width: int) -> Shape:
    """Returns :py:`Shape(width, signed=True)`."""
    ...

class Value(metaclass=ABCMeta):
    """
    Abstract representation of a bit pattern computed in a circuit.

    The Amaranth language gives Python code the ability to create a circuit netlist by manipulating
    objects representing the computations within that circuit. The :class:`Value` class represents
    the bit pattern of a constant, or of a circuit input or output, or within a storage element; or
    the result of an arithmetic, logical, or bit container operation.

    Operations on this class interpret this bit pattern either as an integer, which can be signed
    or unsigned depending on the value's :meth:`shape`, or as a bit container. In either case,
    the semantics of operations that implement Python's syntax, like :py:`+` (also known as
    :meth:`__add__`), are identical to the corresponding operation on a Python :class:`int` (or on
    a Python sequence container). The bitwise inversion :py:`~` (also known as :meth:`__invert__`)
    is the sole exception to this rule.

    Data that is not conveniently representable by a single integer or a bit container can be
    represented by wrapping a :class:`Value` in a :class:`ValueCastable` subclass that provides
    domain-specific operations. It is possible to extend Amaranth in third-party code using
    value-castable objects, and the Amaranth standard library provides several built-in ones:

    * :mod:`amaranth.lib.enum` classes are a drop-in replacement for the standard Python
      :mod:`enum` classes that can be defined with an Amaranth shape;
    * :mod:`amaranth.lib.data` classes allow defining complex data structures such as structures
      and unions.

    Operations on :class:`Value` instances return another :class:`Value` instance. Unless the exact
    type and value of the result is explicitly specified below, it should be considered opaque, and
    may change without notice between Amaranth releases as long as the semantics remains the same.

    .. note::

        In each of the descriptions below, you will see a line similar to:

        **Return type:** :class:`Value`, :py:`unsigned(1)`, :ref:`assignable <lang-assignable>`

        The first part (:class:`Value`) indicates that the returned object's type is a subclass
        of :class:`Value`. The second part (:py:`unsigned(1)`) describes the shape of that value.
        The third part, if present, indicates that the value is assignable if :py:`self` is
        assignable.
    """
    @staticmethod
    def cast(obj: ValueLike) -> Value:
        """
        Cast :py:`obj` to an Amaranth value.

        Many :ref:`value-like <lang-valuelike>` objects can be cast to a value:

        * a :class:`Value` instance, where the result is itself;
        * a :class:`bool` or :class:`int` instance, where the result is :py:`Const(obj)`;
        * an :class:`enum.IntEnum` instance, or a :class:`enum.Enum` instance whose members are
          all integers, where the result is a :class:`Const(obj, enum_shape)` where :py:`enum_shape`
          is a shape that can represent every member of the enumeration;
        * a :class:`ValueCastable` instance, where the result is obtained by repeatedly calling
          :meth:`obj.as_value() <ValueCastable.as_value>`.

        Raises
        ------
        TypeError
            If :py:`obj` cannot be converted to a :class:`Value`.
        RecursionError
            If :py:`obj` is a :class:`ValueCastable` object that casts to itself.
        """
        ...

    def __init__(self, *, src_loc_at=...) -> None: ...
    def __bool__(self) -> NoReturn:
        """
        Forbidden conversion to boolean.

        Python uses this operator for its built-in semantics, e.g. :py:`if`, and requires it to
        return a :class:`bool`. Since this is not possible for Amaranth values, this operator
        always raises an exception.

        Raises
        ------
        :exc:`TypeError`
            Always.
        """
        ...
    def __invert__(self) -> Value:
        """
        Bitwise NOT, :py:`~self`.

        The shape of the result is the same as the shape of :py:`self`, even for unsigned values.

        .. warning::

            In Python, :py:`~0` equals :py:`-1`. In Amaranth, :py:`~C(0)` equals :py:`C(1)`.
            This is the only case where an Amaranth operator deviates from the Python operator
            with the same name.

            This deviation is necessary because Python does not allow overriding the logical
            :py:`and`, :py:`or`, and :py:`not` operators. Amaranth uses :py:`&`, :py:`|`, and
            :py:`~` instead; if it wasn't the case that :py:`~C(0) == C(1)`, that would have
            been impossible.

        Returns
        -------
        :class:`Value`, :py:`self.shape()`
        """
        ...
    def __pos__(self) -> Value:
        """
        Unary position, :py:`+self`.

        Returns
        -------
        :class:`Value`, :py:`self.shape()`
            :py:`self`
        """
        ...
    def __neg__(self) -> Value:
        """
        Unary negation, :py:`-self`.

        ..
            >>> C(-1).value, C(-1).shape()
            -1, signed(1)
            >>> C(-(-1), signed(1)).value # overflows
            -1

        Returns
        -------
        :class:`Value`, :py:`signed(len(self) + 1)`
        """
        ...
    def __add__(self, other: ValueLike) -> Value:
        """
        Addition, :py:`self + other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(self.width(), other.width()) + 1)`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(max(self.width() + 1, other.width()) + 1)`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(max(self.width(), other.width() + 1) + 1)`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(max(self.width(), other.width()) + 1)`
            If both :py:`self` and :py:`other` are unsigned.
        """
        ...
    def __radd__(self, other: ValueLike) -> Value:
        """
        Addition, :py:`other + self` (reflected).

        Like :meth:`__add__`, with operands swapped.
        """
        ...
    def __sub__(self, other: ValueLike) -> Value:
        """
        Subtraction, :py:`self - other`.

        Returns
        -------
        :class:`Value`, :py:`signed(max(self.width(), other.width()) + 1)`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(max(self.width() + 1, other.width()) + 1)`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(max(self.width(), other.width() + 1) + 1)`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(max(self.width(), other.width()) + 1)`
            If both :py:`self` and :py:`other` are unsigned.

        Returns
        -------
        :class:`Value`
        """
        ...
    def __rsub__(self, other: ValueLike) -> Value:
        """
        Subtraction, :py:`other - self` (reflected).

        Like :meth:`__sub__`, with operands swapped.
        """
        ...
    def __mul__(self, other: ValueLike) -> Value:
        """
        Multiplication, :py:`self * other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self) + len(other))`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(len(self) + len(other))`
            If either :py:`self` or :py:`other` are signed.
        """
        ...
    def __rmul__(self, other: ValueLike) -> Value:
        """
        Multiplication, :py:`other * self` (reflected).

        Like :meth:`__mul__`, with operands swapped.
        """
        ...
    def __mod__(self, other: ValueLike) -> Value:
        """
        Flooring modulo or remainder, :py:`self % other`.

        If :py:`other` is zero, the result of this operation is zero.

        Returns
        -------
        :class:`Value`, :py:`other.shape()`
        """
        ...
    def __rmod__(self, other: ValueLike) -> Value:
        """
        Flooring modulo or remainder, :py:`other % self` (reflected).

        Like :meth:`__mod__`, with operands swapped.
        """
        ...
    def __floordiv__(self, other: ValueLike) -> Value:
        """
        Flooring division, :py:`self // other`.

        If :py:`other` is zero, the result of this operation is zero.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self))`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(len(self) + 1)`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(len(self))`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(len(self) + 1)`
            If both :py:`self` and :py:`other` are signed.
        """
        ...
    def __rfloordiv__(self, other: ValueLike) -> Value:
        """
        Flooring division, :py:`other // self` (reflected).

        If :py:`self` is zero, the result of this operation is zero.

        Like :meth:`__floordiv__`, with operands swapped.
        """
        ...
    def __lshift__(self, other: ValueLike) -> Value:
        """
        Left shift by variable amount, :py:`self << other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self) + 2 ** len(other) - 1)`
            If :py:`self` is unsigned.
        :class:`Value`, :py:`signed(len(self) + 2 ** len(other) - 1)`
            If :py:`self` is signed.

        Raises
        ------
        :exc:`TypeError`
            If :py:`other` is signed.
        """
        ...
    def __rlshift__(self, other: ValueLike) -> Value:
        """
        Left shift by variable amount, :py:`other << self`.

        Like :meth:`__lshift__`, with operands swapped.
        """
        ...
    def __rshift__(self, other: ValueLike) -> Value:
        """
        Right shift by variable amount, :py:`self >> other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self))`
            If :py:`self` is unsigned.
        :class:`Value`, :py:`signed(len(self))`
            If :py:`self` is signed.

        Raises
        ------
        :exc:`TypeError`
            If :py:`other` is signed.
        """
        ...
    def __rrshift__(self, other: ValueLike) -> Value:
        """
        Right shift by variable amount, :py:`other >> self`.

        Like :meth:`__rshift__`, with operands swapped.
        """
        ...
    def __and__(self, other: ValueLike) -> Value:
        """
        Bitwise AND, :py:`self & other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(max(self.width() + 1, other.width()))`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(max(self.width(), other.width() + 1))`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        """
        ...
    def __rand__(self, other: ValueLike) -> Value:
        """
        Bitwise AND, :py:`other & self`.

        Like :meth:`__and__`, with operands swapped.
        """
        ...
    def __xor__(self, other: ValueLike) -> Value:
        """
        Bitwise XOR, :py:`self ^ other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(max(self.width() + 1, other.width()))`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(max(self.width(), other.width() + 1))`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        """
        ...
    def __rxor__(self, other: ValueLike) -> Value:
        """
        Bitwise XOR, :py:`other ^ self`.

        Like :meth:`__xor__`, with operands swapped.
        """
        ...
    def __or__(self, other: ValueLike) -> Value:
        """
        Bitwise OR, :py:`self | other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        :class:`Value`, :py:`signed(max(self.width() + 1, other.width()))`
            If :py:`self` is unsigned and :py:`other` is signed.
        :class:`Value`, :py:`signed(max(self.width(), other.width() + 1))`
            If :py:`self` is signed and :py:`other` is unsigned.
        :class:`Value`, :py:`signed(max(self.width(), other.width()))`
            If both :py:`self` and :py:`other` are unsigned.
        """
        ...
    def __ror__(self, other: ValueLike) -> Value:
        """
        Bitwise OR, :py:`other | self`.

        Like :meth:`__or__`, with operands swapped.
        """
        ...
    def __eq__(self, other: ValueLike) -> Value:
        """
        Equality comparison, :py:`self == other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __ne__(self, other: ValueLike) -> Value:
        """
        Inequality comparison, :py:`self != other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __lt__(self, other: ValueLike) -> Value:
        """
        Less than comparison, :py:`self < other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __le__(self, other: ValueLike) -> Value:
        """
        Less than or equals comparison, :py:`self <= other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __gt__(self, other: ValueLike) -> Value:
        """
        Greater than comparison, :py:`self > other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __ge__(self, other: ValueLike) -> Value:
        """
        Greater than or equals comparison, :py:`self >= other`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...
    def __abs__(self) -> Value:
        """
        Absolute value, :py:`abs(self)`.

        ..
            >>> abs(C(-1)).shape()
            unsigned(1)
            >>> C(1).shape()
            unsigned(1)

        Return
        ------
        :class:`Value`, :py:`unsigned(len(self))`
        """
        ...
    def __len__(self) -> int:
        """
        Bit width of :py:`self`.

        Returns
        -------
        :class:`int`
            :py:`self.shape().width`
        """
        ...
    def __getitem__(self, key: int | slice) -> Value:
        r"""
        Bit slicing.

        Selects a constant-width, constant-offset part of :py:`self`. All three slicing syntaxes
        (:py:`self[i]`, :py:`self[i:j]`, and :py:`self[i:j:k]`) as well as negative indices are
        supported. Like with other Python containers, out-of-bounds indices are trimmed to
        the bounds of :py:`self`.

        To select a variable-offset part of :py:`self`, use :meth:`bit_select` or
        :meth:`word_select` instead.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`, :ref:`assignable <lang-assignable>`
            If :py:`key` is an :class:`int`.
        :class:`Value`, :py:`unsigned(j - i)`, :ref:`assignable <lang-assignable>`
            If :py:`key` is a slice :py:`i:j` where :py:`i` and :py:`j` are :class:`int`\ s.
        :class:`Value`, :py:`unsigned(len(range(*slice(i, j, k).indices(len(self)))))`, :ref:`assignable <lang-assignable>`
            If :py:`key` is a slice :py:`i:j:k` where :py:`i`, :py:`j`, and :py:`k` are :class:`int`\ s.
        """
        ...
    def __iter__(self) -> Iterator[Value]: ...
    def __contains__(self, other) -> NoReturn:
        """
        Forbidden membership test operator.

        Python requires this operator to return a :class:`bool`. Since this is not possible
        for Amaranth values, this operator always raises an exception.

        To check membership in a set of constant integer values, use :meth:`matches` instead.

        Raises
        ------
        :exc:`TypeError`
            Always.
        """
        ...
    def __format__(self, format_desc) -> NoReturn:
        """
        Forbidden formatting.

        Since normal Python formatting (f-strings and ``str.format``) must immediately return
        a string, it is unsuitable for formatting Amaranth values. To format a value at simulation
        time, use :class:`Format` instead. If you really want to dump the AST at elaboration time,
        use ``repr`` instead (for instance, via ``f"{value!r}"``).
        """
        ...
    def as_unsigned(self) -> Value:
        """
        Reinterpretation as an unsigned value.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self))`, :ref:`assignable <lang-assignable>`
        """
        ...

    def as_signed(self) -> Value:
        """
        Reinterpretation as a signed value.

        Returns
        -------
        :class:`Value`, :py:`signed(len(self))`, :ref:`assignable <lang-assignable>`

        Raises
        ------
        ValueError
            If :py:`len(self) == 0`.
        """
        ...

    def bool(self) -> Value:
        """
        Conversion to boolean.

        Returns the same value as :meth:`any`, but should be used where :py:`self` is semantically
        a number.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...

    def any(self) -> Value:
        """
        Reduction OR; is any bit :py:`1`?

        Performs the same operation as :meth:`bool`, but should be used where :py:`self` is
        semantically a bit sequence.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...

    def all(self) -> Value:
        """
        Reduction AND; are all bits :py:`1`?

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...

    def xor(self) -> Value:
        """
        Reduction XOR; are an odd amount of bits :py:`1`?

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`
        """
        ...

    def bit_select(self, offset: ValueLike, width: int) -> Value:
        """
        Part-select with bit granularity.

        Selects a constant width, variable offset part of :py:`self`, where parts with successive
        offsets overlap by :py:`width - 1` bits. Bits above the most significant bit of :py:`self`
        may be selected; they are equal to zero if :py:`self` is unsigned, to :py:`self[-1]` if
        :py:`self` is signed, and assigning to them does nothing.

        When :py:`offset` is a constant integer and :py:`offset + width <= len(self)`,
        this operation is equivalent to :py:`self[offset:offset + width]`.

        Parameters
        ----------
        offset: :ref:`value-like <lang-valuelike>`
            Index of the first selected bit.
        width: :class:`int`
            Amount of bits to select.

        Returns
        -------
        :class:`Value`, :py:`unsigned(width)`, :ref:`assignable <lang-assignable>`

        Raises
        ------
        :exc:`TypeError`
            If :py:`offset` is signed.
        :exc:`TypeError`
            If :py:`width` is negative.
        """
        ...

    def word_select(self, offset: ValueLike, width: int) -> Value:
        """
        Part-select with word granularity.

        Selects a constant width, variable offset part of :py:`self`, where parts with successive
        offsets are adjacent but do not overlap. Bits above the most significant bit of :py:`self`
        may be selected; they are equal to zero if :py:`self` is unsigned, to :py:`self[-1]` if
        :py:`self` is signed, and assigning to them does nothing.

        When :py:`offset` is a constant integer and :py:`width:(offset + 1) * width <= len(self)`,
        this operation is equivalent to :py:`self[offset * width:(offset + 1) * width]`.

        Parameters
        ----------
        offset: :ref:`value-like <lang-valuelike>`
            Index of the first selected word.
        width: :class:`int`
            Amount of bits to select.

        Returns
        -------
        :class:`Value`, :py:`unsigned(width)`, :ref:`assignable <lang-assignable>`

        Raises
        ------
        :exc:`TypeError`
            If :py:`offset` is signed.
        :exc:`TypeError`
            If :py:`width` is negative.
        """
        ...

    def matches(self, *patterns: SwitchKey) -> Value:
        """
        Pattern matching.

        Matches against a set of patterns, recognizing the same grammar as :py:`with m.Case()`.
        The pattern syntax is described in the :ref:`language guide <lang-matchop>`.

        Each of the :py:`patterns` may be a :class:`str` or a :ref:`constant-castable object
        <lang-constcasting>`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(1)`

        Raises
        ------
        :exc:`SyntaxError`
            If a pattern has invalid syntax.
        """
        ...

    def shift_left(self, amount: int) -> Value:
        """
        Left shift by constant amount.

        If :py:`amount < 0`, performs the same operation as :py:`self.shift_right(-amount)`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(len(self) + amount, 0))`
            If :py:`self` is unsigned.
        :class:`Value`, :py:`signed(max(len(self) + amount, 1))`
            If :py:`self` is signed.
        """
        ...

    def shift_right(self, amount: int) -> Value:
        """
        Right shift by constant amount.

        If :py:`amount < 0`, performs the same operation as :py:`self.shift_left(-amount)`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(max(len(self) - amount, 0))`
            If :py:`self` is unsigned.
        :class:`Value`, :py:`signed(max(len(self) - amount, 1))`
            If :py:`self` is signed.
        """
        ...

    def rotate_left(self, amount: int) -> Value:
        """
        Left rotate by constant amount.

        If :py:`amount < 0`, performs the same operation as :py:`self.rotate_right(-amount)`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self))`, :ref:`assignable <lang-assignable>`
        """
        ...

    def rotate_right(self, amount: int) -> Value:
        """
        Right rotate by constant amount.

        If :py:`amount < 0`, performs the same operation as :py:`self.rotate_left(-amount)`.

        Returns
        -------
        :class:`Value`, :py:`unsigned(len(self))`, :ref:`assignable <lang-assignable>`
        """
        ...

    def replicate(self, count: int) -> Value:
        """Replication.

        A ``Value`` is replicated (repeated) several times to be used
        on the RHS of assignments::

            len(v.replicate(n)) == len(v) * n

        Parameters
        ----------
        count : int
            Number of replications.

        Returns
        -------
        Value, out
            Replicated value.
        """
        ...

    def eq(self, value: ValueLike) -> Assign:
        r"""
        :ref:`Assignment <lang-assigns>`.

        Once it is placed in a domain, an assignment changes the bit pattern of :py:`self` to
        equal :py:`value`. If the bit width of :py:`value` is less than that of :py:`self`,
        it is zero-extended (for unsigned :py:`value`\ s) or sign-extended (for signed
        :py:`value`\ s). If the bit width of :py:`value` is greater than that of :py:`self`,
        it is truncated.

        Returns
        -------
        :class:`Statement`
        """
        ...

    @abstractmethod
    def shape(self) -> Shape:
        """
        Shape of :py:`self`.

        Returns
        -------
        :ref:`shape-like object <lang-shapelike>`
        """
        ...

    __hash__ = ...

class _ConstMeta(ABCMeta):
    def __call__(cls, value: int | ShapeCastable, shape: Optional[ShapeLike] = ..., src_loc_at=0, **kwargs): ...

@final
class Const(Value, metaclass=_ConstMeta):
    """
    A constant, literal integer value.

    Parameters
    ----------
    value : int
    shape : int or tuple or None
        Either an integer ``width`` or a tuple ``(width, signed)`` specifying the number of bits
        in this constant and whether it is signed (can represent negative values).
        ``shape`` defaults to the minimum possible width and signedness of ``value``.

    Attributes
    ----------
    width : int
    signed : bool
    """

    src_loc = ...
    @staticmethod
    def cast(obj: ValueLike) -> Const:
        """
        Converts ``obj`` to an Amaranth constant.

        First, ``obj`` is converted to a value using :meth:`Value.cast`. If it is a constant, it
        is returned. If it is a constant-castable expression, it is evaluated and returned.
        Otherwise, :exn:`TypeError` is raised.
        """
        ...
    def __init__(self, value: int, shape: Optional[ShapeLike] = ..., *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...

C = Const

class AnyValue(Value, DUID):
    def __init__(self, shape: ShapeLike, *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...

@final
class AnyConst(AnyValue):
    def __repr__(self) -> str:
        """Return repr(self)."""
        ...

@final
class AnySeq(AnyValue):
    def __repr__(self) -> str:
        """Return repr(self)."""
        ...

@final
class Operator(Value):
    def __init__(self, operator: str, operands: Iterable[ValueLike], *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

def Mux(sel: ValueLike, val1: ValueLike, val0: ValueLike) -> Value:
    """
    Choose between two values.

    Parameters
    ----------
    sel : Value, in
        Selector.
    val1 : Value, in
    val0 : Value, in
        Input values.

    Returns
    -------
    Value, out
        Output ``Value``. If ``sel`` is asserted, the Mux returns ``val1``, else ``val0``.
    """
    ...

@final
class Slice(Value):
    def __init__(self, value: ValueLike, start: int, stop: int, *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

    value: Value
    start: int
    stop: int

@final
class Part(Value):
    def __init__(self, value: Value, offset: ValueLike, width: int, stride: int = ..., *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

@final
class Cat(Value):
    """
    Concatenate values.

    Form a compound ``Value`` from several smaller ones by concatenation.
    The first argument occupies the lower bits of the result.
    The return value can be used on either side of an assignment, that
    is, the concatenated value can be used as an argument on the RHS or
    as a target on the LHS. If it is used on the LHS, it must solely
    consist of ``Signal`` s, slices of ``Signal`` s, and other concatenations
    meeting these properties. The bit length of the return value is the sum of
    the bit lengths of the arguments::

        len(Cat(args)) == sum(len(arg) for arg in args)

    Parameters
    ----------
    *args : Values or iterables of Values, inout
        ``Value`` s to be concatenated.

    Returns
    -------
    Value, inout
        Resulting ``Value`` obtained by concatenation.
    """
    def __init__(self, *args: Flattenable[ValueLike], src_loc_at=...) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str:
        """Return repr(self)."""
        ...

@final
class Concat(Value):
    def __init__(self, args: Iterable[ValueLike], src_loc_at=0) -> None: ...
    @property
    def parts(self) -> tuple[Value, ...]: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

@final
class SwitchValue(Value):
    def __init__(
        self,
        test: ValueLike,
        cases: Iterable[tuple[SwitchKey | tuple[SwitchKey, ...] | None, ValueLike]],
        *,
        src_loc=None,
        src_loc_at=0,
    ) -> None: ...
    @property
    def test(self) -> Value: ...
    @property
    def cases(self) -> tuple[tuple[Optional[tuple[str, ...]], Value], ...]: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

@final
class Repl(Value):
    def __init__(self, value: ValueLike, count: int, *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

class _SignalMeta(ABCMeta):
    @overload
    def __call__(cls, shape: type[_T_Enum], src_loc_at: int = ..., **kwargs) -> EnumView[_T_Enum]: ...
    @overload
    def __call__(cls, shape: type[_T_Flag], src_loc_at: int = ..., **kwargs) -> FlagView[_T_Flag]: ...
    @overload
    def __call__(cls, shape: ShapeCastable[T], src_loc_at: int = ..., **kwargs) -> T: ...
    @overload
    def __call__(cls, shape: FlatShapeLike = ..., src_loc_at: int = ..., **kwargs) -> Signal: ...
    def __call__(cls, shape: ShapeLike = ..., src_loc_at: int = ..., **kwargs): ...

class Signal(Value, DUID, metaclass=_SignalMeta):
    """
    A varying integer value.

    Parameters
    ----------
    shape : ``Shape``-castable object or None
        Specification for the number of bits in this ``Signal`` and its signedness (whether it
        can represent negative values). See ``Shape.cast`` for details.
        If not specified, ``shape`` defaults to 1-bit and non-signed.
    name : str
        Name hint for this signal. If ``None`` (default) the name is inferred from the variable
        name this ``Signal`` is assigned to. If the empty string, then this ``Signal`` is treated
        as private and is generally hidden from view.
    init : int or integral Enum
        Reset (synchronous) or default (combinational) value.
        When this ``Signal`` is assigned to in synchronous context and the corresponding clock
        domain is reset, the ``Signal`` assumes the given value. When this ``Signal`` is unassigned
        in combinational context (due to conditional assignments not being taken), the ``Signal``
        assumes its ``init`` value. Defaults to 0.
    reset_less : bool
        If ``True``, do not generate reset logic for this ``Signal`` in synchronous statements.
        The ``init`` value is only used as a combinational default or as the initial value.
        Defaults to ``False``.
    attrs : dict
        Dictionary of synthesis attributes.
    decoder : function or Enum
        A function converting integer signal values to human-readable strings (e.g. FSM state
        names). If an ``Enum`` subclass is passed, it is concisely decoded using format string
        ``"{0.name:}/{0.value:}"``, or a number if the signal value is not a member of
        the enumeration.

    Attributes
    ----------
    width : int
    signed : bool
    name : str
    init : int
    reset_less : bool
    attrs : dict
    decoder : function
    """
    def __init__(
        self,
        shape: Optional[ShapeLike] = ...,
        *,
        name: Optional[str] = ...,
        init: int | Enum = ...,
        reset_less: bool = ...,
        attrs: dict = ...,
        decoder: type[Enum] | Callable[[int], str] = ...,
        src_loc_at=...,
    ) -> None: ...
    @overload
    @staticmethod
    def like(
        other: _T_ValueCastable,
        *,
        name: Optional[str] = ...,
        name_suffix: Optional[str] = ...,
        src_loc_at=...,
        **kwargs,
    ) -> _T_ValueCastable: ...
    @overload
    @staticmethod
    def like(
        other: FlatValueLike, *, name: Optional[str] = ..., name_suffix: Optional[str] = ..., src_loc_at=..., **kwargs
    ) -> Signal: ...
    @staticmethod
    def like(
        other: ValueLike, *, name: Optional[str] = ..., name_suffix: Optional[str] = ..., src_loc_at=..., **kwargs
    ):
        """
        Create Signal based on another.

        Parameters
        ----------
        other : ValueLike
            Object to base this Signal on.
        """
        ...

    def shape(self) -> Shape: ...
    @property
    def init(self) -> int: ...
    @property
    def reset_less(self) -> bool: ...
    @property
    def attrs(self) -> dict: ...
    @property
    def decoder(self) -> type[Enum] | Callable[[int], str]: ...
    def __repr__(self) -> str: ...

    name: str

@final
class ClockSignal(Value):
    """
    Clock signal for a clock domain.

    Any ``ClockSignal`` is equivalent to ``cd.clk`` for a clock domain with the corresponding name.
    All of these signals ultimately refer to the same signal, but they can be manipulated
    independently of the clock domain, even before the clock domain is created.

    Parameters
    ----------
    domain : str
        Clock domain to obtain a clock signal for. Defaults to ``"sync"``.
    """
    def __init__(self, domain: str = ..., *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

@final
class ResetSignal(Value):
    """
    Reset signal for a clock domain.

    Any ``ResetSignal`` is equivalent to ``cd.rst`` for a clock domain with the corresponding name.
    All of these signals ultimately refer to the same signal, but they can be manipulated
    independently of the clock domain, even before the clock domain is created.

    Parameters
    ----------
    domain : str
        Clock domain to obtain a reset signal for. Defaults to ``"sync"``.
    allow_reset_less : bool
        If the clock domain is reset-less, act as a constant ``0`` instead of reporting an error.
    """
    def __init__(self, domain: str = ..., allow_reset_less: bool = ..., *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

class Array(MutableSequence[T]):
    """
    Addressable multiplexer.

    An array is similar to a ``list`` that can also be indexed by ``Value``s; indexing by an integer
    or a slice works the same as for Python lists, but indexing by a ``Value`` results in a proxy.

    The array proxy can be used as an ordinary ``Value``, i.e. participate in calculations and
    assignments, provided that all elements of the array are values. The array proxy also supports
    attribute access and further indexing, each returning another array proxy; this means that
    the results of indexing into arrays, arrays of records, and arrays of arrays can all
    be used as first-class values.

    It is an error to change an array or any of its elements after an array proxy was created.
    Changing the array directly will raise an exception. However, it is not possible to detect
    the elements being modified; if an element's attribute or element is modified after the proxy
    for it has been created, the proxy will refer to stale data.

    Examples
    --------

    Simple array::

        gpios = Array(Signal() for _ in range(10))
        with m.If(bus.we):
            m.d.sync += gpios[bus.addr].eq(bus.w_data)
        with m.Else():
            m.d.sync += bus.r_data.eq(gpios[bus.addr])

    Multidimensional array::

        mult = Array(Array(x * y for y in range(10)) for x in range(10))
        a = Signal.range(10)
        b = Signal.range(10)
        r = Signal(8)
        m.d.comb += r.eq(mult[a][b])

    Array of records::

        layout = [
            ("r_data", 16),
            ("r_en",   1),
        ]
        buses  = Array(Record(layout) for busno in range(4))
        master = Record(layout)
        m.d.comb += [
            buses[sel].r_en.eq(master.r_en),
            master.r_data.eq(buses[sel].r_data),
        ]
    """
    def __init__(self, iterable: Iterable[T] = ()) -> None: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: Value) -> ArrayProxy: ...
    def __getitem__(self, index: int | Value) -> T | ArrayProxy: ...
    def __len__(self) -> int: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def insert(self, index: int, value: T) -> None: ...
    def __repr__(self) -> str: ...

@final
class ArrayProxy(Value):
    elems: Sequence[ValueLike]
    index: Value

    def __init__(self, elems: Sequence[ValueLike], index: ValueLike, *, src_loc_at=...) -> None: ...
    def __getattr__(self, attr: str) -> ArrayProxy: ...
    def __getitem__(self, index: Value | int | str) -> ArrayProxy: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

class ValueCastable:
    """
    Interface class for objects that can be cast to a :class:`Value`.

    Computations in the Amaranth language are described by combining :ref:`value-like objects
    <lang-valuelike>`. Inheriting a class from :class:`ValueCastable` and implementing
    all of the methods described below adds instances of that class to the list of
    value-like objects recognized by the :meth:`Value.cast` method. This is a part of the mechanism
    for seamlessly extending the Amaranth language in third-party code.

    .. note::

        All methods and operators defined by the :class:`Value` class will implicitly cast
        a :class:`ValueCastable` object to a :class:`Value`, with the exception of arithmetic
        operators, which will prefer calling a reflected arithmetic operation on
        the :class:`ValueCastable` argument if it defines one.

        For example, if :py:`value_castable` implements :py:`__radd__`, then
        :py:`C(1) + value_castable` will perform :py:`value_castable.__radd__(C(1))`, and otherwise
        it will perform :py:`C(1).__add__(value_castable.as_value())`.
    """
    def __new__(cls, *args, **kwargs):  # -> Self@ValueCastable:
        ...
    @staticmethod
    def lowermethod(func):  # -> (self: Unknown, *args: Unknown, **kwargs: Unknown) -> Unknown:
        ...
    @abstractmethod
    def as_value(self) -> ValueLike:
        """
        as_value()

        Convert :py:`self` to a :ref:`value-like object <lang-valuelike>`.

        This method is called by the Amaranth language to convert :py:`self` to a concrete
        :class:`Value`. It will usually return a :class:`Value` object, but it may also return
        another value-like object to delegate its functionality.

        This method must be idempotent: when called twice on the same object, the result must be
        exactly the same.

        This method may also be called by code that is not a part of the Amaranth language.

        Returns
        -------
        Any other object recognized by :meth:`Value.cast`.

        Raises
        ------
        Exception
            When the conversion cannot be done. This exception must be propagated by callers,
            either directly or as a cause of another exception.

            It is recommended that, in cases where this method raises an exception,
            the :meth:`shape` method also raises an exception.
        """
        ...
    @abstractmethod
    def shape(self) -> ShapeLike:
        """
        shape()

        Compute the shape of :py:`self`.

        This method is not called by the Amaranth language itself; whenever it needs to discover
        the shape of a value-castable object, it calls :class:`self.as_value().shape()`. However,
        that method must return a :class:`Shape`, and :class:`ValueCastable` subclasses may have
        a richer representation of their shape provided by an instance of a :class:`ShapeCastable`
        subclass. This method may return such a representation.

        This method must be idempotent: when called twice on the same object, the result must be
        exactly the same.

        The following condition must hold:

        .. code::

            Shape.cast(self.shape()) == Value.cast(self).shape()

        Returns
        -------
        A :ref:`shape-like <lang-shapelike>` object.

        Raises
        ------
        Exception
            When the conversion cannot be done. This exception must be propagated by callers,
            either directly or as a cause of another exception.

            It is recommended that, in cases where this method raises an exception,
            the :meth:`as_value` method also raises an exception.
        """
        ...

@final
class Sample(Value):
    def __init__(self, expr: ValueLike, clocks: int, domain: Optional[str], *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

def Past(expr: ValueLike, clocks: int = ..., domain: Optional[str] = ...) -> Sample: ...
def Stable(expr: ValueLike, clocks: int = ..., domain: Optional[str] = ...) -> Value: ...
def Rose(expr: ValueLike, clocks: int = ..., domain: Optional[str] = ...) -> Value: ...
def Fell(expr: ValueLike, clocks: int = ..., domain: Optional[str] = ...) -> Value: ...

@final
class Initial(Value):
    """
    Start indicator, for model checking.

    An ``Initial`` signal is ``1`` at the first cycle of model checking, and ``0`` at any other.
    """
    def __init__(self, *, src_loc_at=...) -> None: ...
    def shape(self) -> Shape: ...
    def __repr__(self) -> str: ...

class _FormatLike:
    def __add__(self, other) -> Format: ...
    def __format__(self, format_desc) -> NoReturn:
        """
        Forbidden formatting.

        ``Format`` objects cannot be directly formatted for the same reason as the ``Value``s
        they contain.
        """
        ...

@final
class Format(_FormatLike):
    def __init__(self, format: str, *args, **kwargs) -> None: ...
    def __repr__(self) -> str: ...

    class Enum(_FormatLike):
        def __init__(
            self,
            value: ValueLike,
            /,
            variants: EnumMeta | Mapping[int, str] | Iterable[tuple[int, str]],
            *,
            name: Optional[str] = ...,
        ): ...
        def __repr__(self) -> str: ...

    class Struct(_FormatLike):
        def __init__(
            self, value: ValueLike, /, fields: Mapping[str, _FormatLike] | Iterable[tuple[str, _FormatLike]]
        ): ...
        def __repr__(self) -> str: ...

    class Array(_FormatLike):
        def __init__(self, value: ValueLike, /, fields: Iterable[_FormatLike]): ...
        def __repr__(self) -> str: ...

class _StatementList(list[Statement]):
    def __repr__(self) -> str: ...

class Statement:
    def __init__(self, *, src_loc_at=...) -> None: ...
    @staticmethod
    def cast(obj: StatementLike) -> _StatementList: ...

@final
class Assign(Statement):
    lhs: Value
    rhs: Value

    def __init__(self, lhs: ValueLike, rhs: ValueLike, *, src_loc_at=...) -> None: ...
    def __repr__(self) -> str: ...

@final
class Print(Statement):
    def __init__(self, *args, sep: str = ..., end: str = ..., src_loc_at=...) -> None: ...
    @property
    def message(self) -> Format: ...
    def __repr__(self) -> str: ...

class Property(Statement):
    class Kind(Enum):
        Assert = ...
        Assume = ...
        Cover = ...

    def __init__(
        self, kind: str | Kind, test: ValueLike, message: Optional[str | Format] = ..., *, src_loc_at=...
    ) -> None: ...
    def __repr__(self) -> str: ...

def Assert(test: ValueLike, message: Optional[str | Format], *, src_loc_at=...) -> Property: ...
def Assume(test: ValueLike, message: Optional[str | Format], *, src_loc_at=...) -> Property: ...
def Cover(test: ValueLike, message: Optional[str | Format], *, src_loc_at=...) -> Property: ...

class Switch(Statement):
    def __init__(
        self,
        test: ValueLike,
        cases: Mapping[SwitchKey, StatementLike],
        *,
        src_loc=...,
        src_loc_at=...,
        case_src_locs=...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class IOValue(metaclass=ABCMeta):
    @staticmethod
    def cast(obj: IOValueLike) -> IOValue: ...
    def __init__(self, *, src_loc_at: int = ...) -> None: ...
    @property
    @abstractmethod
    def metadata(self) -> tuple: ...
    def __getitem__(self, key: int | slice) -> IOValue: ...

@final
class IOPort(IOValue):
    def __init__(
        self,
        width: int,
        *,
        name: Optional[str] = ...,
        attrs: Optional[dict] = ...,
        metadata: Optional[tuple] = ...,
        src_loc_at: int = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def attrs(self) -> dict: ...
    @property
    def metadata(self) -> tuple: ...
    def __repr__(self) -> str: ...

@final
class IOConcat(IOValue):
    def __init__(self, parts: Iterable[IOValue], src_loc_at: int = ...) -> None: ...
    @property
    def parts(self) -> tuple[IOValue]: ...
    def __len__(self) -> int: ...
    @property
    def metadata(self) -> tuple: ...
    def __repr__(self) -> str: ...

@final
class IOSlice(IOValue):
    def __init__(self, value: IOValueLike, start: int, stop: int, *, src_loc_at: int = ...) -> None: ...
    @property
    def value(self) -> IOValue: ...
    @property
    def start(self) -> int: ...
    @property
    def stop(self) -> int: ...
    def __len__(self) -> int: ...
    @property
    def metadata(self) -> tuple: ...
    def __repr__(self) -> str: ...

class _MappedKeyCollection(metaclass=ABCMeta): ...

class _MappedKeyDict(MutableMapping, _MappedKeyCollection):
    def __init__(self, pairs=...) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value):  # -> None:
        ...
    def __delitem__(self, key):  # -> None:
        ...
    def __iter__(self):  # -> Generator[None, None, None]:
        ...
    def __eq__(self, other) -> bool: ...
    def __len__(self):  # -> int:
        ...
    def __repr__(self):  # -> str:
        ...

class _MappedKeySet(MutableSet, _MappedKeyCollection):
    def __init__(self, elements=...) -> None: ...
    def add(self, value):  # -> None:
        ...
    def update(self, values):  # -> None:
        ...
    def discard(self, value):  # -> None:
        ...
    def __contains__(self, value):  # -> bool:
        ...
    def __iter__(self):  # -> Generator[None, None, None]:
        ...
    def __len__(self):  # -> int:
        ...
    def __repr__(self):  # -> str:
        ...

class SignalKey:
    def __init__(self, signal: Signal | ClockSignal | ResetSignal) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __lt__(self, other: SignalKey) -> bool: ...
    def __repr__(self) -> str: ...

class SignalDict(_MappedKeyDict):
    _map_key = ...
    _unmap_key = ...

class SignalSet(_MappedKeySet):
    _map_key = ...
    _unmap_key = ...
