"""
This type stub file was generated by pyright.
"""

__all__ = ["Period"]
from typing import overload


_TIME_UNITS = ...
_FREQUENCY_UNITS = ...
class Period:
    def __init__(self, **kwargs) -> None:
        ...
    
    @property
    def seconds(self) -> float:
        ...
    
    @property
    def milliseconds(self) -> float:
        ...
    
    @property
    def microseconds(self) -> float:
        ...
    
    @property
    def nanoseconds(self) -> float:
        ...
    
    @property
    def picoseconds(self) -> float:
        ...
    
    @property
    def femtoseconds(self) -> int:
        ...
    
    @property
    def hertz(self) -> float:
        ...
    
    @property
    def kilohertz(self) -> float:
        ...
    
    @property
    def megahertz(self) -> float:
        ...
    
    @property
    def gigahertz(self) -> float:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __le__(self, other) -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __gt__(self, other) -> bool:
        ...
    
    def __ge__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __neg__(self) -> Period:
        ...
    
    def __pos__(self) -> Period:
        ...
    
    def __abs__(self) -> Period:
        ...
    
    def __add__(self, other: Period) -> Period:
        ...
    
    def __sub__(self, other: Period) -> Period:
        ...
    
    def __mul__(self, other: Period) -> Period:
        ...
    
    __rmul__ = ...
    
    @overload
    def __truediv__(self, other: float | int) -> float:
        ...
    
    @overload
    def __truediv__(self, other: Period) -> Period:
        ...
    
    def __truediv__(self, other): # -> float | Period | NotImplementedType:
        ...
    
    def __floordiv__(self, other: Period) -> int:
        ...
    
    def __mod__(self, other: Period) -> Period:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __format__(self, format_spec) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


