"""
This type stub file was generated by pyright.
"""

from .._utils import deprecated
from ..hdl._cd import *
from ..hdl._ir import *
from ._pycoro import Tick, Settle, Delay, Passive, Active

__all__ = ["Settle", "Delay", "Tick", "Passive", "Active", "Simulator"]


class Simulator:
    def __init__(self, fragment, *, engine=...) -> None:
        ...
    
    def add_process(self, process): # -> None:
        ...
    
    def add_sync_process(self, process, *, domain=...): # -> None:
        ...
    
    def add_testbench(self, process): # -> None:
        ...
    
    def add_clock(self, period, *, phase=..., domain=..., if_exists=...):
        """Add a clock process.

        Ad"""
        ...
    
    def reset(self): # -> None:
        """Reset the simulation.

        A"""
        ...
    
    @deprecated("instead of `sim.step()`, use `si")
    def step(self): # -> bool:
        ...
    
    def advance(self): # -> bool:
        """Advance the simulation.

       """
        ...
    
    def run(self): # -> None:
        """Run the simulation while any pro"""
        ...
    
    def run_until(self, deadline, *, run_passive=...): # -> None:
        """Run the simulation until it adva"""
        ...
    
    def write_vcd(self, vcd_file, gtkw_file=..., *, traces=...): # -> _GeneratorContextManager[None]:
        """Write waveforms to a Value Chang"""
        ...
    


